spring:
  datasource:
    url: jdbc:mysql://localhost:3306/officehours?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: your_user #will do this later we test now with the dev file no need for account later will setup the database and use the account here
    password: your_pass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
